### ISSUE TITLE
Nvidia Broadcast Installer Thinks No Driver is Installed

### ISSUE THREAD

**Issue by ThisNekoGuy** [Saancreed/wine-nvml#10]
Nvidia Broadcast refuses to install due to thinking that an Nvidia driver isn't installed; not sure of the cause of this

![Screenshot_20221014_155320](https://user-images.githubusercontent.com/28468662/195942334-8072b5b1-f7f6-4010-969e-43ef118c83f8.png)

**Comment by Saancreed** [comment]
I'd say that the installer is correct, unless you do actually have the driver installed in your prefix?

I could be missing something here but how is this a `wine-nvml` issue? Does this program attempt to use it somehow and fails? Which functions does it call? Please check the output of `WINEDEBUG=+loaddll,+nvml` set in the environment where you run `wine` for any lines with `nvml` and post them here.

**Comment by ThisNekoGuy** [comment]
Perhaps I misunderstood the purpose of `wine-nvml`; I expected it to be able to expose the Linux driver to Windows requests seeking driver identification, which sounds to me by your response isn't technically the case and that seeking to get this application to work is... futile?

**Comment by Saancreed** [comment]
The purpose of `wine-nvml` is to forward calls to just that one particular library, NVML. Nvidia's Windows driver contains much, _much_ more than that and if Broadcast wants to have/use anything other than `nvml.dll` then yes, it's out of scope of my project.

**Comment by ThisNekoGuy** [comment]
Sorry about that, then; I'll close.
