### ISSUE TITLE
Steam Proton and libnvidia-ml.so (Question)

### ISSUE THREAD

**Issue by SveSop** [Saancreed/wine-nvml#2]
Is there a easy workaround to get nvml to load libnvidia-ml.so when running a game through Steam/Proton?
`err:nvml:load_nvml Wine cannot find the libnvidia-ml.so library, NVIDIA Management Library support disabled.`

I understand this has to do with soldier/pressure-vessel thingy that kinda run things in a "sandbox" when you run stuff through the steam runtime...

I am currently trying using `Proton-6.10-GE-1`, but still fails with this.

Added nvml.dll/nvml.dll.so and updated the proton script to copy these to the prefix when `PROTON_ENABLE_NVAPI` is set, so it seems nvml.dll is loading correctly tho... Just dlopen'ing libnvidia-ml.so that is kinda stubborn since it probably wont do that from system folders (/usr in particular).
Tips? :)

**Comment by Saancreed** [comment]
If I recall correctly, Pressure Vessel mounts the host filesystem under `/run/host` so it might be possible to load `libnvidia-ml.so` by modifying `nvml.c` to load the library from absolute path like `/run/host/usr/lib/libnvidia-ml.so`, though I'm not sure whether `libnvidia-ml.so` itself won't in turn try to `dlopen` another NV library.

You could try something like [this](https://github.com/wine-staging/wine-staging/blob/master/patches/nvencodeapi-Video_Encoder/0002-nvencodeapi-Add-debian-specific-paths-to-native-libr.patch) patch to keep it compatible with Wine used outside of Pressure Vessel. And of course if this fails too, there's always the possibility of running Proton without Soldier, although very explicitly unsupported by Valve.

**Comment by jp7677** [comment]
May be the last comment here https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/71 would be a way for finding libnvidia-ml.so from inside wine-nvml.

**Comment by SveSop** [comment]
@jp7677 
Not too familiar with pressure-vessel / soldier thing, but mostly this issue was for the proton script to actually find nVidia's included .dll and copy it to the prefix. This is not a problem really.
Without (anyone save nVidia) knowing how/what the nvngx.dll does, i dunno how to approach this i guess.

I mean, even tho /run/host is the mounted os filesystem, i don't know how pressure-vessel loads any linux lib's from there? Does it? Is there some sort of "approved list" of loadable lib's? 
I mean, `libGLX_nvidia.so.0` is for me in /usr/lib/x86_64-linux-gnu for instance.. same as `libnvidia-ml.so` but it is still "not found" when attempted to load from within the pressure-vessel.

Just (since i am quite dense) from the look of it the discussion linked was mere about "finding the .dll and copy it to the prefix". Can't really copy libnvidia-ml.so to the prefix tho... (or whatever more lib's needed).

**Comment by SveSop** [comment]
I know they had similar issues with Mangohud, and it is a lot of stuff posted about that there tho.. Not really gotten around to a neat solution yet.

**Comment by SveSop** [comment]
Maybe some tinkering with stuff in `$HOME/.steam/steam/steamapps/common/SteamLinuxRuntime_soldier/var/deploy-0.20210415.0/files/lib/x86_64-linux-gnu` but that would need tinkering on a per-update-basis i guess.
The libraries inside that folder is not the same as on my "real" system, so i dunno if those are some sort of libs compiled for this purpose (like in a VM)?
`/usr/lib/x86_64-linux-gnu/libX11.so.6.3.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=0c80b4457efd2fd0e56453ae8a58fded7e56fe0f, stripped`
vs the pressure-vessel one: 
`libX11.so.6.3.0: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, BuildID[sha1]=a08f7d65173b68ea8e284cc8f6fd4ff1106ba5ef, stripped`

**Comment by Saancreed** [comment]
> May be the last comment here https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues/71 would be a way for finding libnvidia-ml.so from inside wine-nvml.

That… might be usable for our purposes, but it assumes that `libGLX_nvidia.so` can be found by the dynamic linker or it's already loaded into the process.

In the latter case, maybe something like this could work? (disclaimer: quick–and–dirty code ahead)

```c
#define _GNU_SOURCE
#include <dlfcn.h>
#include <link.h>
#include <linux/limits.h>
#include <stdio.h>
#include <string.h>

int main(void)
{
    void *glx = dlopen("libGLX_nvidia.so", RTLD_LAZY | RTLD_NOLOAD);

    if (!glx)
    {
        fprintf(stderr, "libGLX_nvidia.so not loaded: %s\n", dlerror());
        return 1;
    }

    char path[PATH_MAX];

    if (dlinfo(glx, RTLD_DI_ORIGIN, path))
    {
        fprintf(stderr, "dlinfo() failed: %s\n", dlerror());
        return 2;
    }

    dlclose(glx);
    strcat(path, "/libnvidia-ml.so");

    void *nvml = dlopen(path, RTLD_NOW);

    if (!nvml)
    {
        fprintf(stderr, "failed to load libnvidia-ml.so: %s\n", dlerror());
        return 3;
    }

    puts(path);
    dlclose(nvml);
}
```

**Comment by SveSop** [comment]
I copied `libnvidia-ml.so.470.42.01` into their respective directories `$HOME/.steam/steam/steamapps/common/SteamLinuxRuntime_soldier/var/deploy-0.20210415.0/files/lib/x86_64-linux-gnu` and `i386-linux-gnu`, then symlinked `libnvidia-ml.so -> libnvidia-ml.so.470.42.01`

```
0134:trace:nvml:DllMain (0x7f77d8830000, 1, (nil))
0134:trace:nvml:nvmlInit_v2 ()
0134:trace:nvml:nvmlDeviceGetHandleByPciBusId_v2 (00000000:01:00.0, 0x2018820)
0134:trace:nvml:DllMain (0x7f77d8830000, 0, 0x1)
0134:trace:nvml:nvmlShutdown ()
```
Atleast seems as it loaded from there. I guess the libs in the RT gets built as somewhat "generic libs" or something. 

I don't really understand how stuff works, so i am just spinning my thoughts about the libGLX_nvidia.so thingy above here.. Would not just libGLX.so already have loaded libGLX_nvidia.so "in memory", so that it would not actually use dlopen to do that function? I mean, there is no specific libGLX_nvidia.so loading going on when "soldier" fires up and do its job?
It is a different thing for eg. libvulkan (graphics API), cos it is dynamically loaded (and thus it exist in the aforementioned steam soldier folder aswell). 

Atleast this would make sense to me - thinking of "steam soldier" as a kind of vm, so libraries not loaded (in memory) already has to be in the vm structure so to speak, and stuff existing outside of the folder structure is non-existent...

What options does that leave? 1. Make steamRT include libnvidia-ml.so build with the RT, or 2. Static linking?

**Comment by Saancreed** [comment]
> I don't really understand how stuff works, so i am just spinning my thoughts about the libGLX_nvidia.so thingy above here.. Would not just libGLX.so already have loaded libGLX_nvidia.so "in memory", so that it would not actually use dlopen to do that function? I mean, there is no specific libGLX_nvidia.so loading going on when "soldier" fires up and do its job?
It is a different thing for eg. libvulkan (graphics API), cos it is dynamically loaded (and thus it exist in the aforementioned steam soldier folder aswell).

Well, as I've said, this whole thing is an _assumption_. I'd say it's a safe bet for `libnvidia-ml.so` to be in the same place as `libGLX_nvidia.so`, but _finding_ `libGLX_nvidia.so` itself is not guaranteed to be easy. If it's already loaded (and if we are called by something like `dxvk-nvapi` then it's indeed very likely that NV's Vulkan driver was loaded before we were) then I'd expect it to be quite easy. If that's not the case then we're in a trouble anyway.

In any case, I'd like to avoid any Soldier/PressureVessel–specific workarounds.

> What options does that leave? 1. Make steamRT include libnvidia-ml.so build with the RT,

Doesn't sound like a good idea, Steam Runtime would have to ship, like, hundreds of version of `libnvidia-ml.so` to make sure it one matches installed driver version. Why not use the one available on the host system? It's more or less guaranteed to match NV driver version.

> or 2. Static linking?

So I'd have to rebuild `wine-nvml` whenever I update NV driver (not to mention I'd need object files Nvidia does not ship)? :smile:

Besides, this sounds exactly like something that would be broken by PE split.

**Comment by SveSop** [comment]
> Well, as I've said, this whole thing is an _assumption_. I'd say it's a safe bet for `libnvidia-ml.so` to be in the same place as `libGLX_nvidia.so`, but _finding_ `libGLX_nvidia.so` itself is not guaranteed to be easy. If it's already loaded (and if we are called by something like `dxvk-nvapi` then it's indeed very likely that NV's Vulkan driver was loaded before we were) then I'd expect it to be quite easy. If that's not the case then we're in a trouble anyway.
> 
Well afaik steamRT does not actually "load" libGLX_nvidia.so does it? For me using X11, it is loaded during startup, so there is no need to do anything like `dlopen libGLX_nvidia.so ` from pressure-vessel (and i doubt it does). libGLX.so resides in the aforementioned pressure-vessel "system folder" tho, so it can be loaded/pointed to for various stuff, but i am not sure it is "loaded" the way a dynlib would be. (But i am just speculating about that).
> In any case, I'd like to avoid any Soldier/PressureVessel–specific workarounds.
> 
Sure. But to me it seems it is not "just to point to the right system folder" to load a lib inside pressure-vessel.. I think the intent of the libs inside pressure-vessel is to make sure libs "have what the games need", so it does not have to rely upon whatever custom libs "insert-your-favorite-distro" have. That way, /usr is unavailable so that games cannot try to load regular libs, and is "forced" to use what is configured. 

I think that it is probably not too hard to add such a dependency upon libnvidia-ml.so, but that it would need some upstream changes to steam RT to do so. (see not below about version)

If you look at `~/.steam/steam/steamapps/common/SteamLinuxRuntime_soldier/var/deploy-0.20210415.0/metadata` file, there are `LD_LIBRARY_PATH` setting there for `/app/lib/...` From my understanding just adding /usr/... to that would not work since /usr is unavailable from within pressure-vessel.

> > What options does that leave? 1. Make steamRT include libnvidia-ml.so build with the RT,
> 
> Doesn't sound like a good idea, Steam Runtime would have to ship, like, hundreds of version of `libnvidia-ml.so` to make sure it one matches installed driver version. Why not use the one available on the host system? It's more or less guaranteed to match NV driver version.
> 
IF libnvidia-ml.so is vastly different between driver versions, yes. If eg. the libnvidia-ml.so from the CUDA SDK is usable for static linking it might not have all the new functions (if any) added.. Ill do some testing and see what happens if i put that one in pressure-vessel instead of the one from my system.

> > or 2. Static linking?
> 
> So I'd have to rebuild `wine-nvml` whenever I update NV driver (not to mention I'd need object files Nvidia does not ship)? smile
> 
> Besides, this sounds exactly like something that would be broken by PE split.

I agree on the PE bit for sure, but i static linked libnvidia-ml.so with my old nvapi, and it has been many many updates to drivers on my system since i compiled it last, but it still works for the functions i used it for in my old nvapi. (Frequency, fanspeed++) As i said above, if new stuff gets added, sure that wont work, but i would think the structure and functions of already functions is not changed much unless it is pure bugs. I would expect libnvidia-ml.so from the 450.xx driver to work with 470.xx driver, but it need some testing.

**Comment by SveSop** [comment]
Just tested libnvidia-ml.so from the CUDA-11 SDK, and it is "too old" i guess...
```
0134:trace:nvml:DllMain (0x7ff270080000, 1, (nil))
0134:warn:nvml:load_nvml Can't find symbol nvmlDeviceGetRowRemapperHistogram.
0134:trace:nvml:nvmlInit_v2 ()
```
So, yeah, if static linked, it has to have all the symbols nvml source currently uses. I guess `nvmlDeviceGetRowRemapperHistogram` is something of newer date then, as i cant find it in the CUDA 11 version i have, but it is in `libnvidia-ml.so.470.42.01`

I could not find any changelog of nvml other than "current" and from 349 and back.. (So anything in between 349 -> 460 i have not found a changelog).

**Comment by Saancreed** [comment]
> Well afaik steamRT does not actually "load" libGLX_nvidia.so does it? For me using X11, it is loaded during startup, so there is no need to do anything like `dlopen libGLX_nvidia.so ` from pressure-vessel (and i doubt it does). libGLX.so resides in the aforementioned pressure-vessel "system folder" tho, so it can be loaded/pointed to for various stuff, but i am not sure it is "loaded" the way a dynlib would be. (But i am just speculating about that).
> 
> Sure. But to me it seems it is not "just to point to the right system folder" to load a lib inside pressure-vessel.. I think the intent of the libs inside pressure-vessel is to make sure libs "have what the games need", so it does not have to rely upon whatever custom libs "insert-your-favorite-distro" have. That way, /usr is unavailable so that games cannot try to load regular libs, and is "forced" to use what is configured.

I was mostly betting on applications running inside Steam Runtime still having to load Nvidia Vulkan driver from host libraries, which is why I used `RTLD_NOLOAD` in the sample above. `/usr` inside the container would indeed have container libraries, but from application's POV, if `libGLX_nvidia.so` is loaded (because we are trying to run a game over DXVK / vkd3d-proton?) it should be from path like `/run/host/usr/lib/x86_64-linux-gnu` and this directory should also contain usable `libnvidia-ml.so`.

> If you look at `~/.steam/steam/steamapps/common/SteamLinuxRuntime_soldier/var/deploy-0.20210415.0/metadata` file, there are `LD_LIBRARY_PATH` setting there for `/app/lib/...` From my understanding just adding /usr/... to that would not work since /usr is unavailable from within pressure-vessel.

See above. Are you sure your host `/usr` isn't mounted under `/run/host/usr` inside the container?

> > > What options does that leave? 1. Make steamRT include libnvidia-ml.so build with the RT,
> > 
> > 
> > Doesn't sound like a good idea, Steam Runtime would have to ship, like, hundreds of version of `libnvidia-ml.so` to make sure it one matches installed driver version. Why not use the one available on the host system? It's more or less guaranteed to match NV driver version.
> 
> IF libnvidia-ml.so is vastly different between driver versions, yes. If eg. the libnvidia-ml.so from the CUDA SDK is usable for static linking it might not have all the new functions (if any) added.. Ill do some testing and see what happens if i put that one in pressure-vessel instead of the one from my system.
> 
> > > or 2. Static linking?
> > 
> > 
> > So I'd have to rebuild `wine-nvml` whenever I update NV driver (not to mention I'd need object files Nvidia does not ship)? smile
> > Besides, this sounds exactly like something that would be broken by PE split.
> 
> I agree on the PE bit for sure, but i static linked libnvidia-ml.so with my old nvapi, and it has been many many updates to drivers on my system since i compiled it last, but it still works for the functions i used it for in my old nvapi. (Frequency, fanspeed++) As i said above, if new stuff gets added, sure that wont work, but i would think the structure and functions of already functions is not changed much unless it is pure bugs. I would expect libnvidia-ml.so from the 450.xx driver to work with 470.xx driver, but it need some testing.

Interesting, I wasn't aware that CUDA SDK ships with version of NVML that's works with any driver version. Does it still work even if host does not have `libnvidia-ml.so` installed at all?

> Just tested libnvidia-ml.so from the CUDA-11 SDK, and it is "too old" i guess...
> 
> ```
> 0134:trace:nvml:DllMain (0x7ff270080000, 1, (nil))
> 0134:warn:nvml:load_nvml Can't find symbol nvmlDeviceGetRowRemapperHistogram.
> 0134:trace:nvml:nvmlInit_v2 ()
> ```
> 
> So, yeah, if static linked, it has to have all the symbols nvml source currently uses. I guess `nvmlDeviceGetRowRemapperHistogram` is something of newer date then, as i cant find it in the CUDA 11 version i have, but it is in `libnvidia-ml.so.470.42.01`

Nah, it's just a warning, this particular function will simply be unavailable to calling applications (will always return `NVML_ERROR_FUNCTION_NOT_FOUND`). The only functions that are actually required are loaded by `LOAD_FUNCPTR` macro (just 9 of them).

**Comment by SveSop** [comment]
> 
> I was mostly betting on applications running inside Steam Runtime still having to load Nvidia Vulkan driver from host libraries, which is why I used `RTLD_NOLOAD` in the sample above. `/usr` inside the container would indeed have container libraries, but from application's POV, if `libGLX_nvidia.so` is loaded (because we are trying to run a game over DXVK / vkd3d-proton?) it should be from path like `/run/host/usr/lib/x86_64-linux-gnu` and this directory should also contain usable `libnvidia-ml.so`.
> 
> > If you look at `~/.steam/steam/steamapps/common/SteamLinuxRuntime_soldier/var/deploy-0.20210415.0/metadata` file, there are `LD_LIBRARY_PATH` setting there for `/app/lib/...` From my understanding just adding /usr/... to that would not work since /usr is unavailable from within pressure-vessel.
> 
> See above. Are you sure your host `/usr` isn't mounted under `/run/host/usr` inside the container?
> 
Hmm.. I need to look more into that then.
> 
> Interesting, I wasn't aware that CUDA SDK ships with version of NVML that's works with any driver version. Does it still work even if host does not have `libnvidia-ml.so` installed at all?
> 
> > Just tested libnvidia-ml.so from the CUDA-11 SDK, and it is "too old" i guess...
> > ```
> > 0134:trace:nvml:DllMain (0x7ff270080000, 1, (nil))
> > 0134:warn:nvml:load_nvml Can't find symbol nvmlDeviceGetRowRemapperHistogram.
> > 0134:trace:nvml:nvmlInit_v2 ()
> > ```
> >   
> > So, yeah, if static linked, it has to have all the symbols nvml source currently uses. I guess `nvmlDeviceGetRowRemapperHistogram` is something of newer date then, as i cant find it in the CUDA 11 version i have, but it is in `libnvidia-ml.so.470.42.01`
> 
> Nah, it's just a warning, this particular function will simply be unavailable to calling applications (will always return `NVML_ERROR_FUNCTION_NOT_FOUND`). The only functions that are actually required are loaded by `LOAD_FUNCPTR` macro (just 9 of them).

Oh, it might not be as simple as i thought. I did not look at the nvapi log, and this is what was printed:
```
NVML loaded but initialization failed with error: 
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
WARNING:

You should always run with libnvidia-ml.so that is installed with your
NVIDIA Display Driver. By default it's installed in /usr/lib and /usr/lib64.
libnvidia-ml.so in GDK package is a stub library that is attached only for
build purposes (e.g. machine that you build your application doesn't have
to have Display Driver installed).
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
```
So i guess the libnvidia-ml.so from the CUDA package cannot be used as a drop-in replacement like i thought.

**Comment by jp7677** [comment]
@SveSop May be it is time to drop a question at https://gitlab.steamos.cloud/steamrt/steam-runtime-tools/-/issues
Seeing our discussion, there is a lot of guesswork and assumptions, asking there and presenting our case there might be a faster way to get the correct answers.

**Comment by SveSop** [comment]
@Saancreed 
Right.. so a bit of logging and testing, i found out that pressure-vessel actually creates symlinks to the /run/host/usr/xxx libs in a /overrides/lib/ folder structure.
This i must assume is done to get a sort of unified folder structure maybe? (Since /usr/lib is different between distro's, debian using `/usr/lib/x86_64-linux-gnu` for 64 bit and so on)

If you launch steam with `STEAM_LINUX_RUNTIME_LOG=1 STEAM_LINUX_RUNTIME_VERBOSE=1 steam` you will get a log `~/.steam/steam/steamapps/common/SteamLinuxRuntime_soldier/var/slr-latest.log` 
Snippit from this log is:
```
14:01:36.264447: pressure-vessel-wrap[23598]: D:        '/run/host/usr/lib/x86_64-linux-gnu/libnvidia-ml.so.470.42.01'
14:01:36.264456: pressure-vessel-wrap[23598]: D:        '/overrides/lib/x86_64-linux-gnu/libnvidia-ml.so.1'
```
So, it is creating a symlink to my host system's libnvidia-ml.so.470.42.01 -> libnvidia-ml.so.1

I changed loading in nvml.c to `if (!(libnvidia_ml_handle = dlopen("libnvidia-ml.so.1", RTLD_NOW)))` and that did work.

So, still hanging out there is a couple of questions:
1. nvidia driver for ME atleast, symlinks libnvidia-ml.so -> libnvidia-ml.so.1 -> libnvidia-ml.so.470.42.01 already. Does it do that for all systems?
2. ~~Will this creating of symlinks when starting pressure-vessel on other distro's (arch/RHEL++) symlink these overrides like this in the case of different lib placement?~~ :
```
14:01:36.264447: pressure-vessel-wrap[23598]: D:        '/run/host/usr/lib64/libnvidia-ml.so.470.42.01'
14:01:36.264456: pressure-vessel-wrap[23598]: D:        '/overrides/lib/x86_64-linux-gnu/libnvidia-ml.so.1'
```
EDIT: Scrath 2, cos since this obviously was in the searchpath, it would make no sense for it to not work the same for all distro's. I did not use relative path when using dlopen, so it should be ok.

If the answers to the above ~~2~~ questions is yes - Well.. problem solved then.

**Comment by SveSop** [comment]
When it comes to libnvidia-ml.so.1 it does atleast seem as ubuntu and arch gets this symlinked..
[https://packages.ubuntu.com/focal-updates/amd64/libnvidia-compute-465/filelist](https://packages.ubuntu.com/focal-updates/amd64/libnvidia-compute-465/filelist)
and arch
[https://archlinux.org/packages/extra/x86_64/nvidia-utils/files/](https://archlinux.org/packages/extra/x86_64/nvidia-utils/files/)

**Comment by Saancreed** [comment]
> nvidia driver for ME atleast, symlinks libnvidia-ml.so -> libnvidia-ml.so.1 -> libnvidia-ml.so.470.42.01 already. Does it do that for all systems?

I think it's a safe bet that it does (or at least should, and if not, then it's a distro issue). Looking at the `.manifest` from latest NV driver we have:

```
libnvidia-ml.so.470.42.01 0755 CUDA_LIB NATIVE / MODULE:nvml
libnvidia-ml.so.1 0000 CUDA_SYMLINK NATIVE / libnvidia-ml.so.470.42.01 MODULE:nvml
libnvidia-ml.so 0000 CUDA_SYMLINK NATIVE / libnvidia-ml.so.1 MODULE:nvml
```

So if any distro decides to package it differently than the official installer, it's on them.

And if switching the library name passed to `dlopen` to `…so.1` allows it to be found without issues inside Steam Runtime environment then I'm okay with applying such a change in the repo.
